### PR TITLE
Add an em dash wrapper function

### PR DESCRIPTION
**Pull request by h3h**

### CODE REVIEW

**Comment by avdgaag** [comment]
Thanks for this PR! I’m not sure about this change; Smartypants will already replace `---` with `—` for you. If I’m writing an actual `—` myself, I wouldn’t want a script to replace it with an HTML entity—I’d rather leave the `—`.

Then again, there is an HTML entities function in there so this might be considered part of that (although I’d rather remove it), but then I wouldn’t expect a wrapping `span` tag around the `—`.

**Comment by h3h** [comment]
🤷‍♂️ The span wrapping is to accomplish a proper typographic hair spacing around the em dash. I don't much care about the entity-vs-character aspect. I'd agree that the `—` character is just fine on its own.

**Comment by avdgaag** [comment]
If it’s about achieving the proper spacing, shouldn’t we replace the `span` tag with hair spaces, so that it outputs `&#8202;—&#8202;` (or `&#8202;&mdash;&#8202;` for that matter)?

**Comment by h3h** [comment]
Maybe, though the `span` gives the author control over the spacing via their stylesheet, as different fonts may render hair spaces in non-ideal proportions. (And also allows for authors to omit the spaces entirely if they wish.)

**Pull request closed without merging**
